/* ==========================================================================
   GeoNusa — Config & Constants (config.js)
   ==========================================================================*/

const PONTIANAK_CENTER = [-0.0263, 109.3425];
const DEFAULT_ZOOM = 6;

// Koordinat Fallback Pusat Wilayah
const REGION_CENTER_FALLBACKS = {
  'magelangkab': [-7.4917, 110.2137, 11],
  'magelangkota': [-7.4794, 110.2178, 13],
  'kalbar': [0.1318, 111.0958, 7],
  'ptk': [-0.0263, 109.3425, 12]
};

// Daftar Koleksi Geoportal
const GEOPORTAL_SERVERS = [
  { id: 'ptk', name: 'Geoportal Kota Pontianak', url: 'https://geoportal.pontianak.go.id/geoserver/ows' },
  { id: 'kalbar', name: 'Satu Peta Prov. Kalbar', url: 'https://satupeta.kalbarprov.go.id/geoserver/ows' },
  { id: 'kaltimprov', name: 'JIGD Prov. Kalimantan Timur', url: 'https://jigd.kaltimprov.go.id/geoserver/ows' },
  { id: 'kotimkab', name: 'Geoportal Kab. Kotawaringin Timur', url: 'https://geoportal.kotimkab.go.id/geoserver/wms' },
  { id: 'mahakamulu', name: 'Geoportal Kab. Mahakam Ulu', url: 'https://geoserver-geoportal.mahakamulukab.go.id/geoserver/wms' },
  { id: 'sumbar', name: 'Geoportal Prov. Sumatera Barat', url: 'https://geoportal.sumbarprov.go.id/geoserver/wms' },
  { id: 'bengkuluprov', name: 'Geoportal Prov. Bengkulu', url: 'https://geo.bengkuluprov.go.id/geoserver/palapa/ows' },
  { id: 'jateng', name: 'Satu Peta Prov. Jawa Tengah', url: 'https://satupeta.jatengprov.go.id/geoserver/palapa/wms' },
  { id: 'magelangkab', name: 'Geoportal Kab. Magelang', url: 'https://geoportal.magelangkab.go.id/geoserver/ows' },
  { id: 'magelangkota', name: 'Geoportal Kota Magelang', url: 'https://geoportal.magelangkota.go.id/geoserver/ows' },
  { id: 'klatenkab', name: 'Geoportal Kab. Klaten', url: 'https://geoportal.klaten.go.id/geoserver/wms' },
  { id: 'mojokertokota', name: 'Geoportal Kota Mojokerto', url: 'https://geoportal.mojokertokota.go.id/geoserver/ows' },
  { id: 'bandungkota', name: 'Geoportal Kota Bandung', url: 'https://geodata.bandung.go.id/geoserver/ows' },
  { id: 'jogjakota', name: 'Geoportal Kota Yogyakarta', url: 'https://geoportal.jogjakota.go.id/geoserver/ows' }
];

// Daftar Sumber Daya Alam & Lingkungan (SIMONTANA & BIG)
const SDA_LAYERS = [
  { id: 'simontana_kh', name: 'Peta Kawasan Hutan', type: 'Layer', url: 'https://simontana.kehutanan.go.id/arcgis/rest/services/simontana/kh/MapServer/0' },
  { id: 'simontana_gambut', name: 'Peta Gambut', type: 'Layer', url: 'https://simontana.kehutanan.go.id/arcgis/rest/services/simontana/gambut/MapServer/0' },
  { id: 0, name: 'Peta Penutupan Lahan', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/0' },
  { id: 1, name: 'Peta Air Tanah', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/1' },
  { id: 2, name: 'Peta Ketersediaan Air', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/2' },
  { id: 3, name: 'Penggunaan Tanah 10K', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/3' },
  { id: 4, name: 'Penggunaan Tanah 25K', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/4' },
  { id: 5, name: 'Penggunaan Tanah 50K', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/5' },
  { id: 6, name: 'Peta Lahan Gambut', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/6' },
  { id: 7, name: 'Peta Daerah Aliran Sungai', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/7' },
  { id: 8, name: 'Peta Geologi', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/8' },
  { id: 9, name: 'Peta Geologi Geostruktur', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/9' },
  { id: 10, name: 'Peta Kawasan Rawan Bencana Gunung Api (Titik)', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/10' },
  { id: 11, name: 'Peta Kawasan Rawan Bencana Gunung Api (Area)', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/11' },
  { id: 12, name: 'Peta Kawasan Rawan Bencana Gempa Bumi', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/12' },
  { id: 13, name: 'Peta Zona Kerentanan Gerakan Tanah', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/13' },
  { id: 14, name: 'Peta Kawasan Rawan Bencana Tsunami', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/14' },
  { id: 15, name: 'Peta Hidrogeologi Litogi Akuifer', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/15' },
  { id: 16, name: 'Peta Hidrogeologi Produktivitas Akuifer', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/16' },
  { id: 17, name: 'Peta Curah Hujan', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/17' },
  { id: 18, name: 'Peta Hari Hujan', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/18' },
  { id: 19, name: 'Peta Potensi Energi Angin', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/19' },
  { id: 20, name: 'Peta Potensi Energi Matahari', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/20' },
  { id: 21, name: 'Peta Wilayah Pengelolaan Perikanan RI', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/21' },
  { id: 22, name: 'Peta Jenis dan Kekayaan Perikanan Tangkap WPPNRI', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/22' },
  { id: 23, name: 'Peta Kawasan Bentang Alam Karst', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/23' },
  { id: 24, name: 'Peta Sumber Daya Mineral Logam', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/24' },
  { id: 25, name: 'Peta Sumber Daya Mineral Non Logam', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/25' },
  { id: 26, name: 'Peta Sumber Daya Batubara', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/26' },
  { id: 27, name: 'Peta Sumber Daya Panas Bumi', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/27' },
  { id: 28, name: 'Peta Sistem Lahan Morfologi', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/28' },
  { id: 29, name: 'Peta Morfometri Bentang Lahan', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/29' },
  { id: 30, name: 'Potensi Desa', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/30' },
  { id: 31, name: 'Peta Kawasan Cagar Budaya', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/31' },
  { id: 32, name: 'Peta Sebaran Lokasi Cagar Budaya', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/32' },
  { id: 33, name: 'Peta Zonasi Kawasan Konservasi', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/33' },
  { id: 34, name: 'Peta zonasi kawasan konservasi - Blok Kawasan Konservasi - Skala 1:50.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/34' },
  { id: 35, name: 'Peta Zonasi Kawasan Konservasi Perairan', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/35' },
  { id: 36, name: 'Peta Lahan baku Sawah Nasional skala minimal 1:50.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/36' },
  { id: 37, name: 'Peta Kesatuan Hidrologis Gambut', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/37' },
  { id: 38, name: 'Peta Pemantauan Sampah Laut Skala', type: 'Group', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/38' },
  { id: 39, name: 'Peta Pemantauan Sampah Laut P1', type: 'Sub-Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/39' },
  { id: 40, name: 'Peta Pemantauan Sampah Laut P2', type: 'Sub-Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/40' },
  { id: 41, name: 'Peta Terumbu Karang 1:50.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/41' },
  { id: 42, name: 'Peta Cekungan Air Tanah minimal skala 1:250.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/42' },
  { id: 43, name: 'Peta Kerentanan Likuifaksi skala 1:100.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/43' },
  { id: 44, name: 'Peta Patahan Aktif Indonesia skala 1:50.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/44' },
  { id: 45, name: 'Peta Neraca Sumber Daya Air Skala 1:50.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/45' },
  { id: 46, name: 'Peta Kerentanan Pesisir skala 1:250.000 - 50.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/46' },
  { id: 47, name: 'Peta Rawan Kebakaran Hutan dan Lahan skala 1: 250.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/47' },
  { id: 48, name: 'Peta Fungsi Ekosistem Gambut Skala 1:50.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/48' },
  { id: 49, name: 'Peta Lahan Kritis skala 1:50.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/49' },
  { id: 50, name: 'Peta DDDTLH minimal skala 1:250.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/50' },
  { id: 51, name: 'Peta Potensi Perikanan Budidaya skala 1:50.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/51' },
  { id: 52, name: 'Peta lokasi Danau, Situ dan Embung skala 1:50.000', type: 'Group', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/52' },
  { id: 53, name: 'Danau', type: 'Sub-Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/53' },
  { id: 54, name: 'Embung', type: 'Sub-Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/54' },
  { id: 55, name: 'Situ', type: 'Sub-Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/55' },
  { id: 56, name: 'Peta Lahan Garam Skala 1:25.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/56' },
  { id: 57, name: 'Peta Mangrove Skala 1:25.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/57' },
  { id: 58, name: 'Peta Rawan Banjir Skala 1:50.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/58' },
  { id: 59, name: 'Peta Lahan Sawah yang Dilindungi minimal skala 1:50.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/59' },
  { id: 60, name: 'Peta Seismisitas Gempa Bumi skala 1:50.000 - 1:25.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SUMBER_DAYA_ALAM_DAN_LINGKUNGAN/MapServer/60' }
];

// Daftar 22 Layer Batas Wilayah (BIG)
const BATAS_LAYERS = [
  { id: 0, name: 'Peta Batas Administrasi Provinsi', type: 'Group / Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/0' },
  { id: 1, name: 'Peta Batas Administrasi Kabupaten/Kota (Garis)', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/1' },
  { id: 2, name: 'Peta Wilayah Administrasi Kabupaten/Kota (Area)', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/2' },
  { id: 3, name: 'Peta Wilayah Administrasi Kecamatan', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/3' },
  { id: 4, name: 'Peta Batas Administrasi Desa', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/4' },
  { id: 5, name: 'Peta Batas Darat Negara', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/5' },
  { id: 6, name: 'Peta Batas Laut Negara', type: 'Group', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/6' },
  { id: 7, name: 'Peta Batas Landas Kontinen', type: 'Sub-Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/7' },
  { id: 8, name: 'Peta Batas Laut MOU Fisheries', type: 'Sub-Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/8' },
  { id: 9, name: 'Peta Batas Teritorial', type: 'Sub-Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/9' },
  { id: 10, name: 'Peta Batas ZEE', type: 'Sub-Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/10' },
  { id: 11, name: 'Peta Garis Pangkal', type: 'Sub-Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/11' },
  { id: 12, name: 'Peta Zona Tambahan', type: 'Sub-Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/12' },
  { id: 13, name: 'Peta Sebaran Titik Dasar', type: 'Sub-Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/13' },
  { id: 14, name: 'Peta Sebaran Titik Perjanjian Maritim', type: 'Sub-Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/14' },
  { id: 15, name: 'Peta Wilayah Kerja dan Pengoperasian Pelabuhan Perikanan (Area)', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/15' },
  { id: 16, name: 'Peta Wilayah Kerja dan Pengoperasian Pelabuhan Perikanan (Titik)', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/16' },
  { id: 17, name: 'Peta Wilayah Adat di Perairan Laut', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/17' },
  { id: 18, name: 'Peta Wilayah Kerja dan Wilayah Penugasan Panas Bumi Indonesia skala 1:50.000', type: 'Group', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/18' },
  { id: 19, name: 'Wilayah Kerja Panas Bumi', type: 'Sub-Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/19' },
  { id: 20, name: 'Wilayah Penugasan Survei Pendahuluan dan Eksplorasi', type: 'Sub-Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/20' },
  { id: 21, name: 'Peta Batas Wilayah Administrasi Kewenangan Pengelolaan Sumberdaya Laut Provinsi Skala 1:250.000 - 1:25.000*', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/BATAS_WILAYAH/MapServer/21' }
];

// Daftar 8 Layer Kawasan Khusus & Transmigrasi (BIG)
const TRANSMIGRASI_LAYERS = [
  { id: 0, name: 'Peta Penetapan Kawasan Ekonomi Khusus', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KAWASAN_KHUSUS_DAN_TRANSMIGRASI/MapServer/0' },
  { id: 1, name: 'Peta Kawasan Perdagangan Bebas dan Pelabuhan Bebas', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KAWASAN_KHUSUS_DAN_TRANSMIGRASI/MapServer/1' },
  { id: 2, name: 'Peta Persebaran Lokasi Transmigrasi', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KAWASAN_KHUSUS_DAN_TRANSMIGRASI/MapServer/2' },
  { id: 3, name: 'Peta Persebaran Kawasan Transmigrasi', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KAWASAN_KHUSUS_DAN_TRANSMIGRASI/MapServer/3' },
  { id: 4, name: 'Peta Kawasan Industri Eksisting', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KAWASAN_KHUSUS_DAN_TRANSMIGRASI/MapServer/4' },
  { id: 5, name: 'Peta Kawasan Permukiman Kumuh skala 1:5.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KAWASAN_KHUSUS_DAN_TRANSMIGRASI/MapServer/5' },
  { id: 6, name: 'Peta Sebaran Kegiatan Industri skala 1:50.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KAWASAN_KHUSUS_DAN_TRANSMIGRASI/MapServer/6' },
  { id: 7, name: 'Peta Sebaran Objek Vital Nasional Skala 1:50.000', type: 'Layer', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KAWASAN_KHUSUS_DAN_TRANSMIGRASI/MapServer/7' }
];

// Daftar 74 Layer Kebencanaan BNPB / InaRisk
const KEBENCANAAN_LAYERS = [
  { id: 'bencana_01', name: 'Arah Jalur Evakuasi', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/Arah_jalur_evakuasi/MapServer' },
  { id: 'bencana_02', name: 'Batas Administrasi', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/batas_administrasi/MapServer' },
  { id: 'bencana_03', name: 'DIBI Hidrometeorologi 2015-2024', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/DIBI_Hidromet_2015_2024/MapServer' },
  { id: 'bencana_04', name: 'DIBI Provinsi Hidrometeorologi', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/DIBI_Provinsi_2015_2024_Hidromet/MapServer' },
  { id: 'bencana_05', name: 'Faults New (Sesar/Patahan)', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/Faults_new/MapServer' },
  { id: 'bencana_06', name: 'Faults (Sesar/Patahan)', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/Faults/MapServer' },
  { id: 'bencana_07', name: 'Global Tsunami Modelling', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/global_tsunami_modelling/MapServer' },
  { id: 'bencana_08', name: 'Indeks Bahaya Banjir JBTBPJ', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/INDEKS_BAHAYA_BANJIR_JBTBPJ/MapServer' },
  { id: 'bencana_09', name: 'Indeks Bahaya Banjir Proyeksi JBTBPJ', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/INDEKS_BAHAYA_BANJIR_PROYEKSI_JBTBPJ/MapServer' },
  { id: 'bencana_10', name: 'Indeks Bahaya Banjir Bandang JBTBPJ', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/INDEKS_BAHAYA_BANJIRBANDANG_JBTBPJ/MapServer' },
  { id: 'bencana_11', name: 'Indeks Bahaya Banjir Bandang Proyeksi', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/INDEKS_BAHAYA_BANJIRBANDANG_PROYEKSI_JBTBPJ/MapServer' },
  { id: 'bencana_12', name: 'Indeks Bahaya Tanah Longsor JBTBPJ', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/INDEKS_BAHAYA_TANAHLONGSOR_JBTBPJ/MapServer' },
  { id: 'bencana_13', name: 'Indeks Bahaya Tanah Longsor Proyeksi', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/INDEKS_BAHAYA_TANAHLONGSOR_PROYEKSI_JBTBPJ/MapServer' },
  { id: 'bencana_14', name: 'Indeks Risiko Banjir JBTBPJ', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/INDEKS_RISIKO_BANJIR_JBTBPJ/MapServer' },
  { id: 'bencana_15', name: 'Indeks Risiko Banjir Proyeksi JBTBPJ', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/INDEKS_RISIKO_BANJIR_PROYEKSI_JBTBPJ/MapServer' },
  { id: 'bencana_16', name: 'Indeks Risiko Banjir Bandang JBTBPJ', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/INDEKS_RISIKO_BANJIRBANDANG_JBTBPJ/MapServer' },
  { id: 'bencana_17', name: 'Indeks Risiko Banjir Bandang Proyeksi', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/INDEKS_RISIKO_BANJIRBANDANG_PROYEKSI_JBTBPJ/MapServer' },
  { id: 'bencana_18', name: 'Indeks Risiko Tanah Longsor JBTBPJ', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/INDEKS_RISIKO_TANAHLONGSOR_JBTBPJ/MapServer' },
  { id: 'bencana_19', name: 'Indeks Risiko Tanah Longsor Proyeksi', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/INDEKS_RISIKO_TANAHLONGSOR_PROYEKSI_JBTBPJ/MapServer' },
  { id: 'bencana_20', name: 'Jalur Evakuasi', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/Jalur_evakuasi/MapServer' },
  { id: 'bencana_21', name: 'Klasifikasi DAS KLHK', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/Klasifikasi_DAS_KLHK/MapServer' },
  { id: 'bencana_22', name: 'Labuan Bajo', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/Labuhanbajo/MapServer' },
  { id: 'bencana_23', name: 'Layer Bahaya B3', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_B3/MapServer' },
  { id: 'bencana_24', name: 'Layer Bahaya Banjir 30 Sumatera', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_banjir_30_sumatera/MapServer' },
  { id: 'bencana_25', name: 'Layer Bahaya Banjir 30', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_banjir_30/MapServer' },
  { id: 'bencana_26', name: 'Layer Bahaya Banjir Bandang 30', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_banjir_bandang_30/MapServer' },
  { id: 'bencana_27', name: 'Layer Bahaya Banjir JBTBPJ', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_banjir_JBTBPJ/MapServer' },
  { id: 'bencana_28', name: 'Layer Bahaya Banjir Proyeksi JBTBPJ', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_banjir_proyeksi_JBTBPJ/MapServer' },
  { id: 'bencana_29', name: 'Layer Bahaya Banjir Bandang JBTBPJ', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_banjirbandang_JBTBPJ/MapServer' },
  { id: 'bencana_30', name: 'Layer Bahaya Banjir Bandang Proyeksi', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_banjirbandang_proyeksi_JBTBPJ/MapServer' },
  { id: 'bencana_31', name: 'Layer Bahaya Cuaca Ekstrim 30', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_cuaca_ekstrim_30/MapServer' },
  { id: 'bencana_32', name: 'Layer Bahaya EWP', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_ewp/MapServer' },
  { id: 'bencana_33', name: 'Layer Bahaya Gelombang Ekstrim & Abrasi', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_gelombang_ekstrim_dan_abrasi_30/MapServer' },
  { id: 'bencana_34', name: 'Layer Bahaya Gempa Mikro Jakarta', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_gempa_mikro_jkt/MapServer' },
  { id: 'bencana_35', name: 'Layer Bahaya Gempabumi 30', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_gempabumi_30/MapServer' },
  { id: 'bencana_36', name: 'Layer Bahaya Gempabumi', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_gempabumi/MapServer' },
  { id: 'bencana_37', name: 'Layer Bahaya Kebakaran Hutan & Lahan', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_kebakaran_hutan_dan_lahan_30/MapServer' },
  { id: 'bencana_38', name: 'Layer Bahaya Kekeringan 30', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_kekeringan_30/MapServer' },
  { id: 'bencana_39', name: 'Layer Bahaya Letusan Gunungapi 30', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_letusan_gunungapi_30/MapServer' },
  { id: 'bencana_40', name: 'Layer Bahaya Letusan Gunungapi', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_letusan_gunungapi/MapServer' },
  { id: 'bencana_41', name: 'Layer Bahaya Likuefaksi 30', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_likuefaksi_30/MapServer' },
  { id: 'bencana_42', name: 'Layer Bahaya Multi (2 Bahaya 53 Kab)', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_multi_2_bahaya_53kab/MapServer' },
  { id: 'bencana_43', name: 'Layer Bahaya Multi (3 Bahaya 53 Kab)', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_multi_3_bahaya_53kab/MapServer' },
  { id: 'bencana_44', name: 'Layer Bahaya Multi (8 Bahaya 53 Kab)', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_multi_8_bahaya_53kab/MapServer' },
  { id: 'bencana_45', name: 'Layer Bahaya Tanah Longsor 30', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_tanah_longsor_30/MapServer' },
  { id: 'bencana_46', name: 'Layer Bahaya Tanah Longsor JBTBPJ', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_tanahlongsor_JBTBPJ/MapServer' },
  { id: 'bencana_47', name: 'Layer Bahaya Tanah Longsor Proyeksi', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_tanahlongsor_proyeksi_JBTBPJ/MapServer' },
  { id: 'bencana_48', name: 'Layer Bahaya Tsunami 30', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_bahaya_tsunami_30/MapServer' },
  { id: 'bencana_49', name: 'Layer Kapasitas EWP', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_kapasitas_ewp/MapServer' },
  { id: 'bencana_50', name: 'Layer Kelas Bahaya Multi 2 (53 Kab)', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_kelas_bahaya_multi_2_bahaya_53kab/MapServer' },
  { id: 'bencana_51', name: 'Layer Kelas Bahaya Multi 3 (53 Kab)', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_kelas_bahaya_multi_3_bahaya_53kab/MapServer' },
  { id: 'bencana_52', name: 'Layer Kelas Bahaya Multi 8 (53 Kab)', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_kelas_bahaya_multi_8_bahaya_53kab/MapServer' },
  { id: 'bencana_53', name: 'Layer Kelas H SDK', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/LAYER_KELAS_H_SDK/MapServer' },
  { id: 'bencana_54', name: 'Layer Kelas R SDK', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/LAYER_KELAS_R_SDK/MapServer' },
  { id: 'bencana_55', name: 'Layer Kelas SDK', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/LAYER_KELAS_SDK/MapServer' },
  { id: 'bencana_56', name: 'Layer Kerentanan EWP', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_kerentanan_ewp/MapServer' },
  { id: 'bencana_57', name: 'Layer KRB Gempabumi Mikro Jakarta', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_krb_gempabumi_mikro_jkt/MapServer' },
  { id: 'bencana_58', name: 'Layer PGA MCEG 100', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_PGA_MCEG_100/MapServer' },
  { id: 'bencana_59', name: 'Layer PGA MCER S1 100', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_PGA_MCER_S1_100/MapServer' },
  { id: 'bencana_60', name: 'Layer PGA MCER Ss 100', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_PGA_MCER_Ss_100/MapServer' },
  { id: 'bencana_61', name: 'Layer Risiko Banjir JBTBPJ', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_risiko_banjir_JBTBPJ/MapServer' },
  { id: 'bencana_62', name: 'Layer Risiko Banjir Proyeksi JBTBPJ', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_risiko_banjir_proyeksi_JBTBPJ/MapServer' },
  { id: 'bencana_63', name: 'Layer Risiko Banjir Bandang JBTBPJ', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_risiko_banjirbandang_JBTBPJ/MapServer' },
  { id: 'bencana_64', name: 'Layer Risiko Banjir Bandang Proyeksi', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_risiko_banjirbandang_proyeksi_JBTBPJ/MapServer' },
  { id: 'bencana_65', name: 'Layer Risiko EWP', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_risiko_ewp/MapServer' },
  { id: 'bencana_66', name: 'Layer Risiko Tanah Longsor JBTBPJ', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_risiko_tanahlongsor_JBTBPJ/MapServer' },
  { id: 'bencana_67', name: 'Layer Risiko Tanah Longsor Proyeksi', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/layer_risiko_tanahlongsor_proyeksi_JBTBPJ/MapServer' },
  { id: 'bencana_68', name: 'Peta Bahaya Tsunami Badung', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/Peta_Bahaya_Tsunami_badung/MapServer' },
  { id: 'bencana_69', name: 'Peta Bahaya Tsunami', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/Peta_bahaya_tsunami/MapServer' },
  { id: 'bencana_70', name: 'Peta Rencana Evakuasi Cilacap', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/Peta_Rencana_Evakuasi_Cilacap1/MapServer' },
  { id: 'bencana_71', name: 'PGA 2017 10 50', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/PGA_2017_10_50/MapServer' },
  { id: 'bencana_72', name: 'Renevak Tsunami', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/RENEVAK_tsunami/MapServer' },
  { id: 'bencana_73', name: 'Simulated Landslide Tsunami', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/Slimulated_landslide_tsunami/MapServer' },
  { id: 'bencana_74', name: 'ZRB Multibahaya', url: 'https://gis.bnpb.go.id/server/rest/services/inarisk/ZRB_Multibahaya/MapServer' }
];

const KEHUTANAN_LAYERS = [
  { id: 0, name: 'Penetapan Kawasan Hutan', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KEHUTANAN/MapServer/0', type: 'Layer' },
  { id: 1, name: 'Kawasan Hutan Dengan Tujuan Khusus', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KEHUTANAN/MapServer/1', type: 'Layer' },
  { id: 2, name: 'Hutan Tanaman Rakyat', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KEHUTANAN/MapServer/2', type: 'Layer' },
  { id: 3, name: 'Hutan Adat', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KEHUTANAN/MapServer/3', type: 'Layer' },
  { id: 4, name: 'Neraca Sumber Daya Hutan', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KEHUTANAN/MapServer/4', type: 'Group' },
  { id: 5, name: 'Neraca Sumber Daya Hutan Fungsi Kawasan Hutan', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KEHUTANAN/MapServer/5', type: 'Sub-Layer' },
  { id: 6, name: 'Neraca Sumber Daya Hutan Penutup Lahan', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KEHUTANAN/MapServer/6', type: 'Sub-Layer' },
  { id: 7, name: 'Peta Pelepasan Kawasan Hutan', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KEHUTANAN/MapServer/7', type: 'Layer' },
  { id: 8, name: 'Peta Persetujuan Penggunaan Kawasan Hutan', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KEHUTANAN/MapServer/8', type: 'Group' },
  { id: 9, name: 'Operasi Produksi dan Non Tambang', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KEHUTANAN/MapServer/9', type: 'Sub-Layer' },
  { id: 10, name: 'Eksplorasi', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KEHUTANAN/MapServer/10', type: 'Sub-Layer' },
  { id: 11, name: 'Peta Indikatif Penyelesaian Penguasaan Tanah Dalam Rangka Penataan Kawasan Hutan', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KEHUTANAN/MapServer/11', type: 'Layer' },
  { id: 12, name: 'Persetujuan Pengelolaan Hutan Kemasyarakatan', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KEHUTANAN/MapServer/12', type: 'Layer' },
  { id: 13, name: 'Persetujuan Pengelolaan Hutan Desa (PPHD)', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KEHUTANAN/MapServer/13', type: 'Layer' },
  { id: 14, name: 'Peta Rawan Erosi', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/KEHUTANAN/MapServer/14', type: 'Layer' }
];

const PERIZINAN_PERTANAHAN_LAYERS = [
  { id: 0, name: 'Peta Izin Pemanfaatan Kawasan Hutan', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/0', type: 'Group' },
  { id: 1, name: 'IUPHHKHA', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/1', type: 'Sub-Layer' },
  { id: 2, name: 'IUPHHKHTI', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/2', type: 'Sub-Layer' },
  { id: 3, name: 'IUPHHKRE', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/3', type: 'Sub-Layer' },
  { id: 4, name: 'Peta Wilayah Izin Usaha Pertambangan', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/4', type: 'Layer' },
  { id: 5, name: 'Peta Wilayah Kerja Migas', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/5', type: 'Group' },
  { id: 6, name: 'Peta Wilayah Kerja Migas Konvensional', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/6', type: 'Sub-Layer' },
  { id: 7, name: 'Peta Wilayah Kerja Migas Non Konvensional', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/7', type: 'Sub-Layer' },
  { id: 8, name: 'Peta Indikatif Penghentian Pemberian Izin Baru skala 1:250.000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/8', type: 'Layer' },
  { id: 9, name: 'Peta Izin Pengelolaan Hutan Perhutanan Sosial (IPHPS)', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/9', type: 'Layer' },
  { id: 10, name: 'Peta Penggunaan dan Kepemilikan Tanah (Hak Milik) Skala 1: 5000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/10', type: 'Group' },
  { id: 11, name: 'Nusa Tenggara Barat', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/11', type: 'Sub-Layer' },
  { id: 12, name: 'Jawa Timur', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/12', type: 'Sub-Layer' },
  { id: 13, name: 'Daerah Istimewa Yogyakarta', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/13', type: 'Sub-Layer' },
  { id: 14, name: 'Kalimantan Barat', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/14', type: 'Sub-Layer' },
  { id: 15, name: 'Sulawesi Barat', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/15', type: 'Sub-Layer' },
  { id: 16, name: 'Kalimantan Utara', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/16', type: 'Sub-Layer' },
  { id: 17, name: 'Aceh', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/17', type: 'Sub-Layer' },
  { id: 18, name: 'Sulawesi Tenggara', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/18', type: 'Sub-Layer' },
  { id: 19, name: 'Maluku', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/19', type: 'Sub-Layer' },
  { id: 20, name: 'Kalimantan Timur', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/20', type: 'Sub-Layer' },
  { id: 21, name: 'Jawa Barat', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/21', type: 'Sub-Layer' },
  { id: 22, name: 'Bali', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/22', type: 'Sub-Layer' },
  { id: 23, name: 'Banten', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/23', type: 'Sub-Layer' },
  { id: 24, name: 'Kepulauan Riau', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/24', type: 'Sub-Layer' },
  { id: 25, name: 'Jawa Tengah', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/25', type: 'Sub-Layer' },
  { id: 26, name: 'Peta Perizinan Usaha Bidang Perkebunan', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/26', type: 'Group' },
  { id: 27, name: 'Izin Lokasi', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/27', type: 'Group' },
  { id: 28, name: 'Peta Izin Lokasi Sawit Bovendigoel', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/28', type: 'Sub-Layer' },
  { id: 29, name: 'Peta Izin Lokasi Sawit Jayapura', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/29', type: 'Sub-Layer' },
  { id: 30, name: 'Peta Izin Lokasi Sawit Keerom', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/30', type: 'Sub-Layer' },
  { id: 31, name: 'Peta Izin Lokasi Sawit Mappi', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/31', type: 'Sub-Layer' },
  { id: 32, name: 'Peta Izin Lokasi Sawit Merauke', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/32', type: 'Sub-Layer' },
  { id: 33, name: 'Peta Izin Lokasi Sawit Mimika', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/33', type: 'Sub-Layer' },
  { id: 34, name: 'Peta Izin Lokasi Sawit Nabire', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/34', type: 'Sub-Layer' },
  { id: 35, name: 'Peta Izin Lokasi Sawit Sarmi', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/35', type: 'Sub-Layer' },
  { id: 36, name: 'Peta Izin Lokasi Sawit Kutai Barat', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/36', type: 'Sub-Layer' },
  { id: 37, name: 'Peta Izin Lokasi Sawit Kutai Kartanegara', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/37', type: 'Sub-Layer' },
  { id: 38, name: 'Peta Izin Lokasi Sawit Kutai Timur', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/38', type: 'Sub-Layer' },
  { id: 39, name: 'Peta Izin Lokasi Sawit Paser', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/39', type: 'Sub-Layer' },
  { id: 40, name: 'Peta Izin Lokasi Sawit Bengkalis', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/40', type: 'Sub-Layer' },
  { id: 41, name: 'Peta Izin Lokasi Sawit Indragiri Hilir', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/41', type: 'Sub-Layer' },
  { id: 42, name: 'Peta Izin Lokasi Sawit Indragiri Hulu', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/42', type: 'Sub-Layer' },
  { id: 43, name: 'Peta Izin Lokasi Sawit Kampar', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/43', type: 'Sub-Layer' },
  { id: 44, name: 'Peta Izin Lokasi Sawit Kuantan Singingi', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/44', type: 'Sub-Layer' },
  { id: 45, name: 'Peta Izin Lokasi Sawit Rokan Hilir', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/45', type: 'Sub-Layer' },
  { id: 46, name: 'Peta Izin Lokasi Sawit Rokan Hulu', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/46', type: 'Sub-Layer' },
  { id: 47, name: 'Peta Izin Lokasi Sawit Siak', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/47', type: 'Sub-Layer' },
  { id: 48, name: 'Peta Izin Lokasi Sawit Mamuju', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/48', type: 'Sub-Layer' },
  { id: 49, name: 'Peta Izin Lokasi Sawit Mamuju Tengah', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/49', type: 'Sub-Layer' },
  { id: 50, name: 'Izin Usaha', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/50', type: 'Group' },
  { id: 51, name: 'Peta Izin Usaha Sawit Bovendigoel', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/51', type: 'Sub-Layer' },
  { id: 52, name: 'Peta Izin Usaha Sawit Jayapura', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/52', type: 'Sub-Layer' },
  { id: 53, name: 'Peta Izin Usaha Sawit Keerom', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/53', type: 'Sub-Layer' },
  { id: 54, name: 'Peta Izin Usaha Sawit Merauke', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/54', type: 'Sub-Layer' },
  { id: 55, name: 'Peta Izin Usaha Sawit Mimika', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/55', type: 'Sub-Layer' },
  { id: 56, name: 'Peta Izin Usaha Sawit Nabire', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/56', type: 'Sub-Layer' },
  { id: 57, name: 'Peta Izin Usaha Sawit Sarmi', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/57', type: 'Sub-Layer' },
  { id: 58, name: 'Peta Neraca Penatagunaan Tanah skala 1:50.000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/58', type: 'Layer' },
  { id: 59, name: 'Peta Penetapan Lokasi Pengadaan Tanah bagi Kepentingan Umum Skala 1:50.000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/59', type: 'Layer' },
  { id: 60, name: 'Peta Zona Nilai Tanah minimal skala 1:10.000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/PERIZINAN_DAN_PERTANAHAN/MapServer/60', type: 'Layer' }
];

const SARANA_PRASARANA_LAYERS = [
  { id: 0, name: 'Peta Lokasi Pelabuhan Perikanan', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/0', type: 'Layer' },
  { id: 1, name: 'Peta Sebaran Pelabuhan Umum', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/1', type: 'Layer' },
  { id: 2, name: 'Peta Sebaran Pelabuhan Penyeberangan', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/2', type: 'Layer' },
  { id: 3, name: 'Peta Sebaran Terminal Khusus', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/3', type: 'Layer' },
  { id: 4, name: 'Peta Sebaran Bandara', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/4', type: 'Layer' },
  { id: 5, name: 'Peta Sebaran Jaringan Rel dan Stasiun KA', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/5', type: 'Group' },
  { id: 6, name: 'Peta Sebaran Jaringan Rel', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/6', type: 'Sub-Layer' },
  { id: 7, name: 'Peta Sebaran Stasiun KA', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/7', type: 'Sub-Layer' },
  { id: 8, name: 'Peta Jaringan Listrik', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/8', type: 'Layer' },
  { id: 9, name: 'Peta Sebaran Lokasi Gardu Induk', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/9', type: 'Layer' },
  { id: 10, name: 'Peta Lokasi Pembangkit Listrik', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/10', type: 'Layer' },
  { id: 11, name: 'Peta Sebaran Pembangkit Listrik', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/11', type: 'Layer' },
  { id: 12, name: 'Peta Jalan Nasional Tol dan Jalan Nasional Non Tol', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/12', type: 'Group' },
  { id: 13, name: 'Peta Jalan Nasional Non Tol', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/13', type: 'Sub-Layer' },
  { id: 14, name: 'Peta Jalan Nasional Tol', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/14', type: 'Sub-Layer' },
  { id: 15, name: 'Peta Sebaran Lokasi Tempat Pemrosesan Akhir (TPA)', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/15', type: 'Layer' },
  { id: 16, name: 'Peta Sebaran Lokasi Instalasi Pengolahan Air Limbah (IPAL)', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/16', type: 'Layer' },
  { id: 17, name: 'Peta Sebaran Lokasi Instalasi Pengolahan Lumpur Tinja (IPLT)', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/17', type: 'Layer' },
  { id: 18, name: 'Peta Sebaran Lokasi SPAM', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/18', type: 'Layer' },
  { id: 19, name: 'Peta Sebaran Lokasi Bendungan Eksisting', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/19', type: 'Layer' },
  { id: 20, name: 'Peta Sebaran Lokasi Bendungan Rencana', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/20', type: 'Layer' },
  { id: 21, name: 'Peta Sebaran Lokasi Sabo DAM', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/21', type: 'Layer' },
  { id: 22, name: 'Peta Sebaran Lokasi Pengaman Pantai', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/22', type: 'Layer' },
  { id: 23, name: 'Peta Sebaran Lokasi Rusunawa', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/23', type: 'Layer' },
  { id: 24, name: 'Peta Sebaran Terminal Bahan Bakar Minyak dan Terminal LPG skala 1:50.000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/24', type: 'Group' },
  { id: 25, name: 'TERMINAL BBM', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/25', type: 'Sub-Layer' },
  { id: 26, name: 'TERMINAL LPG', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/26', type: 'Sub-Layer' },
  { id: 27, name: 'Peta Lokasi Kilang Minyak skala 1:50.000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/27', type: 'Layer' },
  { id: 28, name: 'Peta Sebaran Pasar Rakyat dan Pasar Desa', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/28', type: 'Layer' },
  { id: 29, name: 'Peta Alur Pelayaran Laut skala 1:50.000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/29', type: 'Layer' },
  { id: 30, name: 'Peta Ruang Udara skala 1:50.000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/30', type: 'Layer' },
  { id: 31, name: 'Peta Daerah Lingkungan Kerja dan Lingkungan Kepentingan Pelabuhan skala 1:50.000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/31', type: 'Layer' },
  { id: 32, name: 'Peta Kawasan Keamanan Operasional Penerbangan (KKOP) skala 1:5.000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/32', type: 'Layer' },
  { id: 33, name: 'Peta Sarana Bantu Navigasi Pelayaran skala 1:50.000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/33', type: 'Layer' },
  { id: 34, name: 'Peta Daerah Irigasi Rawa skala 1:5.000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/34', type: 'Group' },
  { id: 35, name: 'DIR-Potensial', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/35', type: 'Sub-Layer' },
  { id: 36, name: 'DIR-Fungsional', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/36', type: 'Sub-Layer' },
  { id: 37, name: 'DIR-Baku', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/37', type: 'Sub-Layer' },
  { id: 38, name: 'Peta Daerah Irigasi Tambak skala 1:5.000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/38', type: 'Group' },
  { id: 39, name: 'DIT-Potensial', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/39', type: 'Sub-Layer' },
  { id: 40, name: 'DIT-Fungsional', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/40', type: 'Sub-Layer' },
  { id: 41, name: 'DIT-Baku', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/41', type: 'Sub-Layer' },
  { id: 42, name: 'Peta Sebaran Gudang dan Pusat Distribusi Skala 1:50.000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/42', type: 'Group' },
  { id: 43, name: 'Peta Sebaran Gudang', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/43', type: 'Sub-Layer' },
  { id: 44, name: 'Peta Sebaran Pusat Distribusi', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/44', type: 'Sub-Layer' },
  { id: 45, name: 'Peta Sebaran Lokasi Akses Layanan Keuangan skala 1:50.000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/45', type: 'Layer' },
  { id: 46, name: 'Peta Aset Tanah, Gedung dan Bangunan Milik BUMN minimal skala 1:50.000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/46', type: 'Layer' },
  { id: 47, name: 'Peta Kawasan Gudang BUMN skala 1:50.000', url: 'https://kspservices.big.go.id/satupeta/rest/services/PUBLIK/SARANA_PRASARANA/MapServer/47', type: 'Layer' }
];

const BASEMAPS = {
  osm: {
    name: 'OpenStreetMap',
    url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
    options: { 
      attribution: '&copy; OpenStreetMap contributors', 
      maxZoom: 19 
    }
  },
  'esri-satellite': {
    name: 'Satelit Esri',
    url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
    options: { 
      attribution: 'Esri', 
      maxZoom: 19,
      crossOrigin: true 
    }
  },
  'esri-dark-gray': {
    name: 'Esri Dark Gray',
    url: 'https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Base/MapServer/tile/{z}/{y}/{x}',
    options: { attribution: 'Esri', maxZoom: 19 }
  }
};